name: Remote Assistant
version: 1.0.0
schema: v1

models:
  - name: Gemma4:4b
    provider: ollama
    model: gemma3:4b
    apiBase: http://localai.app.vpc.home.arpa:11434
    roles:
      - chat
      - edit
      - apply
      - autocomplete

  - name: llama3.2:latest
    provider: ollama
    model: llama3.2:latest
    apiBase: http://localai.app.vpc.home.arpa:11434
    roles:
      - chat
      - edit
      - apply
      - autocomplete

  - name: qwen3-coder:30b
    provider: ollama
    model: qwen3-coder:30b
    apiBase: http://localai.app.vpc.home.arpa:11434
    roles:
      - chat
      - edit
      - apply
      - autocomplete

context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
