# Author: Logan Mancuso | LastEdit: 2026-03-23

format = """
$os$shell$terraform$directory$git_branch$git_status 
$cmd_duration$character\
"""

[line_break]
disabled = true

[character]
success_symbol = '[❯](bold #A6E3A1)'
error_symbol = '[❯](bold #F38BA8)'
format = '$symbol '
disabled = false

[os]
format = '[$symbol ]($style)'
style = 'fg:#FFFFFF'
disabled = false 

[os.symbols]
Linux = '󰌽'
Windows = ''
Macos = ''

[shell]
zsh_indicator = "󰬡"
bash_indicator = "󱆃"
powershell_indicator = "\ue683"
style = 'fg:#FFFFFF'
disabled = false

[terraform]
format = '[$workspace ]($style)'
style = 'fg:#B4BEFE'

[directory]
style = 'fg:#E8A2AF'
format = '[$path ]($style)'
truncation_length = 2

[git_branch]
symbol = ''
style = 'fg:#A6E3A1'
format = '[$symbol$branch]($style)'

[git_status]
style = 'fg:#A6E3A1'
format = '([$all_status$ahead_behind]($style))'

[cmd_duration]
min_time = 2000
style = 'fg:#FAB387'
format = '[󰔛 $duration ]($style)'